### ISSUE TITLE
Do you have a plan to let koyeb deploy github's repo directly?

### ISSUE THREAD

**Issue by quaggalinux** [koyeb/example-tailscale#1]
Do you have a plan to let koyeb deploy github's repo directly? It will allow "example-tailscale"  easily deploy to koyeb just like Railway and Okteto.

Also, are you planing to write a NGINX or Caddy deploy sample?

Thanks！

**Comment by NoKriK** [comment]
Hey @quaggalinux 👋 

Did you see the [Deploy to Koyeb button](https://github.com/koyeb/example-tailscale#deploy-using-the-koyeb-button) in the readme? This looks like what you're looking for.
This is already available but not documented yet, you can track progress here: https://feedback.koyeb.com/feature-requests/p/deploy-to-koyeb-button

What do you have in mind with an Nginx/Caddy sample? Static hosting?

**Comment by quaggalinux** [comment]
@NoKriK , Thank you for your reply!  
Does the "Deploy to Koyeb button" let Koyeb use Dockerfile in github's repo to build a new docker image and deploy to Koyeb?  
If the answer is yes, I think this button has too many URL parameters compare to heroku's deploy button.  
I want to deploy a NGINX or Caddy static host if this "Deploy to Koyeb button" is working as my understanding.   
  
Thanks,

**Comment by edouardb** [comment]
@quaggalinux the button allows you to deploy an app on Koyeb from a GitHub repository or using a public Docker image from any container registry.

The documentation should be live by the end of the week.

**Comment by quaggalinux** [comment]
@edouardb Thank you for your fantastic work!  
I will learn about the document when it posted.

**Comment by NoKriK** [comment]
Hey @quaggalinux  👋 

The documentation is available [here](https://www.koyeb.com/docs/deploy-to-koyeb-button).

Let us know if you need anything else,
